Change git -C to git --git-dir
jonasmalacofilho/git-cache-http-server pull request #20
Opened 2020-03-30 14:34 UTC by woyczek

Fix defect #19

2020-03-30 16:42 UTC, jonasmalacofilho requested changes
What version of `git` do you have?

I can't reproduce your issue on 2.26.0, and I don't see anything on the changelog for 2.27.0 suggesting the `-C` options has been removed.

2020-03-30 16:42 UTC, jonasmalacofilho commented on src/Main.hx
> +			ChildProcess.exec('git -git-dir "$local" fetch --quiet', callback);
Both are missing a dash here (i.e. `--git-dir`, not `-git-dir`).

2020-03-30 17:35 UTC, jonasmalacofilho commented
Oh, sorry, the git version was in the title of your issue... 1.8.3.1.  As it turns out `git -C` was only [introduced](https://github.com/git/git/commit/44e1e4d67d5148c245db362cc48c3cc6c2ec82ca) in 1.8.5.  

Any chance you can update to a newer version?

If you can't (please let me know why), I don't think I see any problem in merging this (after you fix the minor problem I noticed).

2020-04-06 05:06 UTC, jonasmalacofilho commented
Ping @woyczek.

2020-04-18 13:02 UTC, closed without merging

2020-05-07 12:03 UTC, woyczek commented
﻿No, absolutely no chance, since it is a bulk product from packaged RHEL

— 
This machine has no brain.
Use your own.

Gaétan Ryckeboer

>> Le 30 mars 2020 à 19:35, Jonas Malaco <notifications@github.com> a écrit :
> ﻿
> Oh, sorry, the git version was in the title of your issue... 1.8.3.1. As it turns out git -C was only introduced in 1.8.5.
> 
> Any chance you can update to a newer version?
> 
> If you can't (please let me know why), I don't think I see any problem in merging this (after you fix the minor problem I noticed).
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.